### ISSUE TITLE
Remove lego translations for trace notification emails

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2268]
Moving https://trac.openstreetmap.org/ticket/5032 here for visibility.

The trace notification emails are made from 'lego' translations, that is fragments of sentences stuck together with other data in between each fragment. You can get the idea of how they are hard to translate from the [relevant part of en.yml](https://github.com/openstreetmap/openstreetmap-website/blob/31edc7dff6f4305366d0f93d35ba3fb1956bb71f/config/locales/en.yml#L1149-L1163):

```
    gpx_notification:
      greeting: "Hi,"
      your_gpx_file: "It looks like your GPX file"
      with_description: "with the description"
      and_the_tags: "and the following tags:"
      and_no_tags: "and no tags."
      failure:
        subject: "[OpenStreetMap] GPX Import failure"
        failed_to_import: "failed to import. Here is the error:"
        more_info_1: "More information about GPX import failures and how to avoid"
        more_info_2: "them can be found at:"
        import_failures_url: "https://wiki.openstreetmap.org/wiki/GPX_Import_Failures"
      success:
        subject: "[OpenStreetMap] GPX Import success"
        loaded_successfully: loaded successfully with %{trace_points} out of a possible %{possible_points} points.
```
They should be refactored to use full sentences with the additional data in string interpolation variables e.g. `%{data}`. This allows translators to rearrange the word order, if necessary, as well as making life easier than when trying to translate fragments in isolation (e.g. 'them can be found at:'!).
