### ISSUE TITLE
Fallback processing for community name i18n

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3814]
It looks like our fallback process for the community name i18n isn't sufficient. The osm-community-index has some extra complexity and indirection that nobody noticed during development.

Let's say we are viewing the site in Polish, and looking at the OpenStreetMap France chapter.

https://github.com/osmlab/osm-community-index/blob/main/resources/europe/france/fr-chapter.json
```json
  "id": "fr-chapter",
  "type": "osm-lc",
```

So we want to find out the name of the chapter, we look for `fr-chapter` in the pl.yaml file:

https://github.com/osmlab/osm-community-index/blob/main/i18n/pl.yaml

```yaml
  de-viersen-meetup:
    name: Spotkania OpenStreetMap Viersen
    description: Spotkania społeczności i użytkowników OSM z Viersen i Mönchengladbach
  fr-chapter:
    description: Pomagamy rozwijać i ulepszać OpenStreetMap we Francji.
  fr-matrix:
    description: 'Kanał społeczności OSM France na Matriksie: {url} (połączony z Telegramem)'
```

Note that there's a description, but there's **no name attribute**. It turns out that the name attributes are optional, as part of a process to reduce translation duplication. 

Since there's no name attribute, we can look up what the fallback should be for our object, which is an `osm-lc`:

```yaml
_defaults:
    ...
    osm:
      name: '{community}'
    osm-lc:
      name: '{community}'
    reddit:
      name: '{community} na Reddit'
      url: https://www.reddit.com/r/{account}
```

OK, so for local chapters, the name defaults to the community name. And in the `_communities` list, there's a bunch of community names, e.g. 

```yaml
_communities:
    geolibres: GeoLibres
    kiribatiwomeninmapping: Kobiety z Kiribati Mapujące
    mappingbotswana: Mapowanie Botswany
    ...
    openstreetmapfinland: OpenStreetMap Finlandia
    openstreetmapfrance: OpenStreetMap Francja
    openstreetmapfreemapslovakia: Strona Freemap Słowacja
```

So that's where we're supposed to get the name for the local chapter. 

But the missing piece of the puzzle for me is how do we find out the community to use (in this case `openstreetmapfrance`)? There's no link that I can find between `fr-chapter` and `openstreetmapfrance`. In fact the `openstreetmapfrance` key is only found in the translations and not elsewhere in the osm-community-index repo.
