### ISSUE TITLE
Help for translators with interpolation

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3939]
In a [commit comment](https://github.com/openstreetmap/openstreetmap-website/commit/c7e9888bb6587649109d0c8d9e00c771da867cf9#commitcomment-101769123), @Nikerabbit writes:

> These changes are really difficult for translators because they are create patchwork messages. Especially without accompanying message documentation.
> 
> More docs:
> 
>     https://translatewiki.net/wiki/Translating:Localisation_for_developers#Message_documentation
>     https://www.mediawiki.org/wiki/Help:System_message#Avoid_fragmented_or_'patchwork'_messages
> 
> To be fair, we have the same issue in MediaWiki. Often it can be addressed by using wikitext, but some cases that is not possible. Best would be inline syntax that handles context-dependent escaping. For example:
> 
>     messages:
>     signup_message: Please ${elem|sign up}
> 
> code using fake PHP syntax as I am not familiar with Ruby:
> 
>     t( 'signup_message', function ( $label ) { return makeButton( 'someurl', htmlspecialchars( $label ) ); } );
> 
> But in the meantime, I hope message doc can be added cross-linking the translatable messages to each other.

I'm opening this issue to explore what we can do to make it easier for our translators to handle translations with interpolations. The most common usage of the interpolations are for links, where the link text is used by a link helper and then interpolated into the rest of the sentence, for example:

```yaml
en:
  diary_entries:
    show:
      login_to_leave_a_comment_html: '%{login_link} to leave a comment'
      login: Login
```

```ruby
t(".login_to_leave_a_comment_html", :login_link => link_to(t(".login"), login_path(:referer => request.fullpath)))
```

I'm currently working on a series of PRs to remove all the raw html from the translations, and so this interpolation approach is also being used for html within sentences (bold, emphasis etc) like:
```yaml
en:
  site:
    welcome:
      whats_on_the_map:
        off_the_map_html: |
          What it %{doesnt} include is opinionated data like ratings, historical or
          hypothetical features, and data from copyrighted sources. Unless you have special
          permission, don't copy from online or paper maps.
        doesnt: doesn't
```
```ruby
t ".whats_on_the_map.off_the_map_html", :doesnt => tag.em(t(".whats_on_the_map.doesnt"))
```

**Comment by tomhughes** [comment]
I didn't really understand @Nikerabbit's code, not because I don't know PHP (though I don't) but because it's not clear what the `t` function does with the callback - when does it call it? What does it pass as the argument?

As far as I know they rails i18n stuff doesn't have anything like that anyway.

**Comment by gravitystorm** [comment]
I think @Nikerabbit was trying to illustrate an approach something like this: https://github.com/iGEL/it

**Comment by tomhughes** [comment]
That looks nice - shame it seems to be a bit dormant.

**Comment by lonvia** [comment]
This approach could cause some headache for translators. Using another sentence from the new bold versions:

```
 en:
  site:
    welcome:
      whats_on_the_map:
        on_the_map_html: |
          OpenStreetMap is a place for mapping things that are both %{real_and_current}. ...
        real_and_current: real and current
```

The German translation would go:

```
 en:
  site:
    welcome:
      whats_on_the_map:
        on_the_map_html: |
          OpenStreetMap ist ein Ort, um Dinge zu erfassen, die sowohl %{real_and_current} sind ....
        real_and_current: echt als auch aktuell
```

But that's not really what you would want. You would want: OpenStreetMap ist ein Ort, um Dinge zu mappen die sowohl **echt** als auch **aktuell** sind. `sowohl ... als auch ..` is a standing expression here. In the German version the bold section would ideally be split. In addition, it might make a difference if the interpolated thing is a link something emphasized when it comes to translations. (e.g. word order in German can be changed to emphasize). So it would be good to know that.

Have you considered using a simplified markdown? Most people are familiar with the `**...**` notation nowadays and can follow it. You can also use a simplified version for links: `[Login](login_link) to leave a comment.`

(NB: The English texts are are really difficult to translate as is, because they use unusual and complicated sentence structures. Rewording into simpler English might solve some of the problems as well.)
