### ISSUE TITLE
Further rework lego messages for trace notification emails

### ISSUE THREAD

**Issue by Pikse** [openstreetmap/openstreetmap-website#4012]
In #2268 an effort was made to reduce lego messages. However it appears trace notification emails still include lego messages.

Here sentence beginning and ending are glued together without allowing different ordering in translations:

```
<p>
  <%= render :partial => "gpx_description" %>
  <%= t(".loaded", :trace_points => @trace_points, :count => @possible_points) %>
</p>
```

```
<p>
  <%= render :partial => "gpx_description" %>
  <%= t ".failed_to_import" %>
</p>
```

**Comment by gravitystorm** [comment]
Thanks @Pikse for pointing this out.

The tricky part here is that the long trace descriptions (there are two variations, one with tags and one without) are used in two different sentences, one positive (with countable variations) and one negative.

```yaml
gpx_description:
  description_with_tags_html: "It looks like your GPX file %{trace_name} with the description %{trace_description} and the following tags: %{tags}"
  description_with_no_tags_html: "It looks like your GPX file %{trace_name} with the description %{trace_description} and no tags"
gpx_failure:
  failed_to_import: "failed to import. Here is the error:"
gpx_success:
  loaded:
    one: "loaded successfully with %{trace_points} out of a possible %{count} point."
    other: "loaded successfully with %{trace_points} out of a possible %{count} points."
```

One solution would be maintain the current structure of the translations, but use interpolation e.g. `%{gpx_description} failed to import.` I don't know whether this would be suitable for all languages though, perhaps some of the descriptions need different grammar depending on whether the sentence is positive or negative.

An alternative solution would be to have four full sentence to translate (two failures, two successes). That has a lot of duplication between the sentences, but allows full control over both the word order and also any grammar changes needed to the description based on the positive/negative grammar of the sentence.
