### ISSUE TITLE
Automatically generate PTv2 relations name

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/openstreetmap-website#4033]
### Problem

Currently most PTv2 relations have `network`, `ref`, `route`, `from`, `via` and `to` tags. Regardless of these tags the OSM website shows only the ref of these relations. Using that information it is possible to generate a name like iD and JOSM do.

To make it easier, you can use the strings from iD's implementation (https://github.com/openstreetmap/iD/pull/8276/files):
```
display_name:
      direction: "{direction}"
      from_to: "from {from} to {to}"
      from_to_via: "from {from} to {to} via {via}"
      network_direction: "{network} {direction}"
      network_from_to: "{network} from {from} to {to}"
      network_from_to_via: "{network} from {from} to {to} via {via}"
      ref: "{ref}"
      ref_direction: "{ref} {direction}"
      ref_from_to: "{ref} from {from} to {to}"
      ref_from_to_via: "{ref} from {from} to {to} via {via}"
      network_ref: "{network} {ref}"
      network_ref_direction: "{network} {ref} {direction}"
      network_ref_from_to: "{network} {ref} from {from} to {to}"
      network_ref_from_to_via: "{network} {ref} from {from} to {to} via {via}"
```

Example elements for testing:
https://www.openstreetmap.org/relation/13892501
https://www.openstreetmap.org/relation/13892502
https://www.openstreetmap.org/relation/13892503 (see members section)

### Screenshots

![image](https://github.com/openstreetmap/openstreetmap-website/assets/19364673/1ad3e3a7-f5d4-4cfd-9e0c-e927a9364966)
![image](https://github.com/openstreetmap/openstreetmap-website/assets/19364673/51f96ac1-8020-4042-a6b6-da1fae993403)
