### ISSUE TITLE
Unread messages do not have green background

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/openstreetmap-website#4312]
### URL

https://www.openstreetmap.org/messages/inbox

### How to reproduce the issue?

1. Go to your inbox
2. Mark any message as unread
3. (notice the lack of the green background on that row)

### Screenshot(s) or anything else?

Possibly related to https://github.com/openstreetmap/openstreetmap-website/pull/4262. The class `inbox-row-unread` is being applied to the row but it is overwritten by styles for the cells that come from Bootstrap. Namely:

```css
.table > :not(caption) > * > * {
  ...
  background-color: var(--bs-table-bg);
  ...
}
```

![image](https://github.com/openstreetmap/openstreetmap-website/assets/19364673/dba74b59-8ba3-4928-8e96-e25155630731)
