### ISSUE TITLE
Incorrect translation choice time_ago for 21 hours ago

### ISSUE THREAD

**Issue by deevroman** [openstreetmap/openstreetmap-website#5878]
### How to reproduce the issue?

0. Enable Russian localization
1. Try searching on https://www.openstreetmap.org/history a 25-hour edit

The translation is shown for a string that corresponds to 1 hour ago

### Screenshot(s) or anything else?

<img width="885" src="https://github.com/user-attachments/assets/8d28ac17-c91c-42bc-a922-f589916541f3" />

**Comment by gravitystorm** [comment]
This is a problem in the `ru` (and perhaps other) translations. The translators have hard-coded the "specifically one" translation into the "numbers that behave like one" key:

```yaml
  datetime:
    distance_in_words_ago:
      about_x_hours:
        one: около часа назад
        few: около %{count} часов назад
        many: около %{count} часов назад
```

In Russian, the `one` key is also used for numbers like 21:

```ruby
I18n.with_locale("ru") do
  helper.friendly_date_ago(Time.now - 21.hours)
end
=> "<time title=\" 1 апреля 2025 в 20:16\" datetime=\"2025-04-01T20:16:22+01:00\">около часа назад</time>"
```

Without being able to read or write Russian, and just using Google Translate, it might be possible to fix here:

> около 1 часа назад
> около 21 часа назад

So this translation could simply be updated to be "около %{count} часа назад". Can you confirm this would work grammatically?
