### ISSUE TITLE
Untranslatable strings 4

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#6091]
In https://www.openstreetmap.org/profile:
* "Social profile links"
* "Company"
* "Home location name"

These strings are only in English and there are no messages for them on Translatewiki.

**Comment by hlfan** [comment]
Please take a look at these links:
- https://translatewiki.net/w/i.php?title=Special:Search&search=Osm:Profiles.show.social+links.title
- https://translatewiki.net/w/i.php?title=Special:Search&search=Osm:Users.show.company
- https://translatewiki.net/w/i.php?title=Special:Search&search=Osm:Activerecord.attributes.user.company

As for the home location name I don't have a clue.

**Comment by mmd-osm** [comment]
"Home location name" doesn't appear to be translated at all, try https://www.openstreetmap.org/profile?locale=fr or https://www.openstreetmap.org/profile?locale=de

It would have to be added to config/locales/en.yml under en -> activerecord -> attributes -> user -> home_location_name

**Comment by tomhughes** [comment]
Added in a59490d53964dbfa9fdb0b846a8726e7c1ca7119.

**Comment by maro-21** [comment]
> Please take a look at these links:
> 
> * https://translatewiki.net/w/i.php?title=Special:Search&search=Osm:Profiles.show.social+links.title
> * https://translatewiki.net/w/i.php?title=Special:Search&search=Osm:Users.show.company
> * https://translatewiki.net/w/i.php?title=Special:Search&search=Osm:Activerecord.attributes.user.company

No. These ones are used in other places. And "Social profile links" is not the same as "Social Profile Links".

**Comment by mmd-osm** [comment]
https://translatewiki.net/w/i.php?title=Special:Search&search=Osm:Profiles.show.social+links.title and https://translatewiki.net/w/i.php?title=Special:Search&search=Osm:Activerecord.attributes.user.company appear to be the correct links, see below.

> And "Social profile links" is not the same as "Social Profile Links".

That's a Rails thing. It **is** the same here. I don't know why these rules don't apply to "Home Location Name", which is shown as is (ie. without changing capitalization).

```yml
diff --git a/config/locales/en.yml b/config/locales/en.yml
index 70b5f317e..f53c6e16a 100644
--- a/config/locales/en.yml
+++ b/config/locales/en.yml
@@ -150,7 +150,7 @@ en:
         active: "Active"
         display_name: "Display Name"
         description: Profile Description
-        company: Company
+        company: Company2
         home_lat: Latitude
         home_lon: Longitude
         home_location_name: Home Location Name
@@ -2001,7 +2001,7 @@ en:
       delete: "Delete"
       undelete: "Undo delete"
       social_links:
-        title: Social Profile Links
+        title: Social Profile Links2
         remove: Remove
         add: Add Social Link
     update:
```


![Image](https://github.com/user-attachments/assets/63f3dc53-b74e-47c9-95a5-d3e4016c4475)
